version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  mcp-server-function:
    lang: python3-http
    handler: ./mcp-server-function
    image: exode1/mcp-server-function:latest

